### ISSUE TITLE
Post

### ISSUE THREAD

**Issue by tshimsthedoor** [tshimsthedoor/ThedoorCode#12]

**Comment by tshimsthedoor** [comment]
Here we need the database to have this in post :
- Title
- Description
- Image
- Location
- Latitude
- Longitude
- Author
- Review

**Comment by tshimsthedoor** [comment]
- [ ] Title
- [ ] Description
- [ ] Image
- [ ] Location
- [ ] Longitude
- [ ] Author
- [ ] Review

**Comment by DevStarOps** [comment]
@tshimsthedoor for tasks you need to put them in the description, from the ellipse you are able to click and then edit to put the tasks in 🙂, if you have them where they are at the moment they are not tracked as part of the issue

![image](https://user-images.githubusercontent.com/5680199/167266489-12734530-7354-4676-9613-eb39a9b30e84.png)

**Comment by tshimsthedoor** [comment]
@DevStarOps thank you so much I think that I adjust it.
