### ISSUE TITLE
Replace sample razor pages app with MVC Web App with Auth

### ISSUE THREAD

**Issue by DevStarOps** [tshimsthedoor/ThedoorCode#34]
Remember to pull the models that you've already done out the app to not lose it

![image](https://user-images.githubusercontent.com/5680199/167457403-d75b78d2-7adb-4447-9715-74d0dd71b69d.png)

![image](https://user-images.githubusercontent.com/5680199/167457671-d0dc5819-a818-4703-ae19-3de7d43b9c46.png)

**Comment by tshimsthedoor** [comment]
I replaced the sample app with the Web App with Auth and I am happy with the result.

**Comment by tshimsthedoor** [comment]
Happy with my new MVC model
