### ISSUE TITLE
I can not delete because I am meeting the error.

### ISSUE THREAD

**Issue by tshimsthedoor** [tshimsthedoor/ThedoorCode#54]
- [ ] #60

**Comment by tshimsthedoor** [comment]
Here is what I am seeing when I want to delete a record
![image](https://user-images.githubusercontent.com/16034869/172859197-aff199f9-0d29-4080-be4f-21691f07b660.png)

**Comment by DevStarOps** [comment]
Implement a soft delete delete rather then row delete to get around this

When you list the users show all that are not 'deleted'

**Comment by tshimsthedoor** [comment]
I tried to implement the soft delete but I saw an error that isDeleted column is missing from my schema. And I spend a lot of time reviewing it but...

**Comment by tshimsthedoor** [comment]
I can delete first from experience table then from user table
![image](https://user-images.githubusercontent.com/16034869/173579212-cd0e3df3-44d9-4469-a959-39743af71b10.png)

**Comment by tshimsthedoor** [comment]
I closed this so the new one can be openfor week 11
